[package]
name = "QRterm-rust"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "QRterm-rust"
path = "src/QRterm-rust.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.12.0"
qr2term = "0.2.0"

